DROP TABLE IF EXISTS badges CASCADE;
DROP TABLE IF EXISTS quiztype CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS userbadges;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS leaderboard;