INSERT INTO continents (name) values
('Africa'),
('Asia'),
('Europe'),
('North America'),
('South America'),
('Oceania');

INSERT INTO badgetype (name) values
('Leaderboard Submit'),
('World'),
('Continent'),
('Community Quiz');

INSERT INTO badges (typeid, continentId, name, description, imageUrl, background, border) values
(1, null, 'Competitor', 'Submit a leaderboard entry.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f3c6.svg', '#FFF1CE', '#C1694F'),
(2, null, 'International Traveler', 'Complete all world quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f9f3.svg', '#A8D9FF', '#4289C1'),
(3, 1, 'SaharanBuff', 'Complete all Africa quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f418.svg', '#DDDDDD', '#66757F'),
(3, 2, 'OrientalBuff', 'Complete all Asia quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f338.svg', '#FFE4EA', '#EA596E'),
(3, 3, 'EuropaBuff', 'Complete all Europe quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f3f0.svg', '#ECF3F9', '#226699'),
(3, 4, 'RockiesBuff', 'Complete all North America quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/26f0.svg', '#E9E9E9', '#4B545D'),
(3, 5, 'AmazonBuff', 'Complete all South America quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f483.svg', '#FFBFC7', '#A0041E'),
(3, 6, 'PacificBuff', 'Complete all Oceania quizzes.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f3dd.svg', '#D3ECFF', '#F4900C'),
(4, null, 'Sharing is Caring', 'Create a community quiz.', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f91d.svg', '#276f86', '#000000');

INSERT INTO avatarTypes (name) values
('Commando'),
('Traveller'),
('Researcher');

INSERT INTO avatars (typeId, countryCode, name, description, primaryImageUrl, secondaryImageUrl, gridPlacement) values
(1, 'nz', 'Sarg', 'After a 20 year stint in the NZSAS, Sarg spent some time smuggling precious stones into all those places that are on the tip of your tongue and rather difficult to spell. Cool, calm, collected and very handy with a zipwire; I keep my distance once this man''s on a Countries of the World roll. I advise you do the same...', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-one-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-one-secondary.svg', 4),
(1, 'us', 'Cypher', 'Bona fide hacker and rare NFT collector Cypher cut her teeth toying with Wall St. bankers before becoming the head of operations at the FBI. Word on the street is she lost her eye at 16 when a pirated mint of the original CryptoPunks went horribly wrong. Get a little bit too close to her score on the leaderboard and watch it get ''adjusted'' to zero in no time.', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-two-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-two-secondary.svg', 7),
(2, 'au', 'RoboGazza', 'Is he a man or is he a robot? No-one living knows. With a particular aptitude for shooting things with a bow and bombing hills on his bike, Gazza isn''t a man you want on your tail. Well travelled and well-seasoned; keep this in mind before going head-to-head with him on Flags of the World.', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-one-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-one-secondary.svg', 8),
(2, 'gb-eng', 'Kathy2.0', 'A Yorkshire clone resulting from an experiment run by GeoBuff Research Institute at an undisclosed location off the British coastline. The intent was to genetically increase VO2 max and number of steps per day, and increase it we did. Kathy has walked the Pennines start to finish 7 times this year. Speaking of, has anyone seen the original Kathy?', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-two-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-two-secondary.svg', 2),
(3, 'zm', 'Professor Lungu', 'Top of his class at MIT and hell-bent on being the only academic to publish a paper for the esteemed school AND score max points on Countries of the World in under 5 minutes. Sharp as a tack and quick as a whippet; don''t underestimate the power of a nerd on a mission.', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-one-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-one-secondary.svg', 3),
(3, 'mx', 'Sanchez', 'Ex-champion Jarabe dancer in her home Mexico City, Sanchez was taken under Prof. Lungu''s wing as a field researcher after he discovered she has a photographic memory and is the only person alive that can spell Kyrgyzstan correctly on the first try. Dance with Miss Sanchez, and well, it may just be your last...', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-two-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-two-secondary.svg', 6),
(1, 'fj', 'Willy', 'Born and raised on the Coral Coast, Willy represented Fiji internationally in Sevens before hanging up his boots to pursue a captaincy on the Sea Shepherd chasing pirates all across the Pacific. Strong as an ox and deeply knowledgable of the oceanography of the seven seas, give this man a hearty Bula next time you see him, otherwise it may be time to walk the plank...', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-three-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/commando-three-secondary.svg', 1),
(2, 'cn', 'Ling', 'As an orphan who spent her formattive years stowed away on the Orient Express, Ling developed a particular talent for pickpocketing and mastering foreign languages. Forever on the move sharing her spoils of war with the street children of Shanghai through to Cairo, keep your eyes peeled for a train conductor donning a Jade exterior. It may be the last you see of that expensive wristwatch...', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-three-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/traveller-three-secondary.svg', 5),
(3, 'gb-sct', 'John John', 'They say good things come in small packages but JJ McClay is a reminder that sometime the old adages don''t always prove fruitful (It seems Dunkeld haggis is particularly vitamin-heavy). This 6''8 giant-of-a-man rounds out Prof Lungu''s team of researchers as the formitive expert on Climatology. When he''s not out on assignment in a faraway land, you''ll find him bird-watching in the Cairngorms or serving up bass-thumping tunes in the underground clubs of Edinburgh or Glasgow.', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-three-primary.svg', 'https://geobuff.sgp1.digitaloceanspaces.com/avatars/researcher-three-secondary.svg', 9);

INSERT INTO quiztype (name) values
('Map'),
('Flag');

INSERT INTO quizzes (typeId, badgeId, continentId, country, singular, name, maxScore, time, mapSVG, imageUrl, plural, apiPath, route, hasLeaderboard, hasGrouping, hasFlags, enabled) values
(1, 2, null, '', 'country', 'Countries of the World', 197, 900, 'WorldCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'countries', 'world-countries', 'countries-of-the-world', TRUE, TRUE, TRUE, TRUE),
(1, 2, null, '', 'capital', 'Capitals of the World', 197, 900, 'WorldCapitals', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'capitals', 'world-capitals', 'capitals-of-the-world', TRUE, TRUE, TRUE, TRUE),
(1, 2, null, '', 'continent', 'Continents of the World', 7, 300, 'WorldContinents', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'continents', 'world-continents', 'continents-of-the-world', FALSE, FALSE, FALSE, TRUE),
(1, 2, null, '', 'ocean', 'Oceans of the World', 5, 300, 'WorldOceans', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'oceans', 'world-oceans', 'oceans-of-the-world', FALSE, FALSE, FALSE, TRUE),
(1, 2, null, '', 'mountain', 'Seven Summits', 7, 300, 'SevenSummits', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'mountains', 'seven-summits', 'seven-summits', FALSE, FALSE, TRUE, TRUE),
(1, 2, null, '', 'river', 'Longest Rivers of the World', 10, 300, 'WorldLongestRivers', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'rivers', 'world-longest-rivers', 'longest-rivers-of-the-world', FALSE, FALSE, TRUE, TRUE),
(1, 3, 1, '', 'country', 'Countries of Africa', 54, 300, 'AfricaCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/africa-countries-header.svg', 'countries', 'africa-countries', 'countries-of-africa', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, '', 'country', 'Countries of Asia', 50, 300, 'AsiaCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/asia-countries-header.svg', 'countries', 'asia-countries', 'countries-of-asia', TRUE, FALSE, TRUE, TRUE),
(1, 5, 3, '', 'country', 'Countries of Europe', 51, 300, 'EuropeCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/europe-countries-header.svg', 'countries', 'europe-countries', 'countries-of-europe', TRUE, FALSE, TRUE, TRUE),
(1, 6, 4, '', 'country', 'Countries of North America', 23, 300, 'NorthAmericaCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/north-america-countries-header.svg', 'countries', 'north-america-countries', 'countries-of-north-america', TRUE, FALSE, TRUE, TRUE),
(1, 7, 5, '', 'country', 'Countries of South America', 12, 300, 'SouthAmericaCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/south-america-countries-header.svg', 'countries', 'south-america-countries', 'countries-of-south-america', TRUE, FALSE, TRUE, TRUE),
(1, 8, 6, '', 'country', 'Countries of Oceania', 15, 300, 'OceaniaCountries', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/oceania-countries-header.svg', 'countries', 'oceania-countries', 'countries-of-oceania', TRUE, FALSE, TRUE, TRUE),
(1, 7, 5, 'Argentina', 'province', 'Provinces of Argentina', 24, 300, 'ArgentinaProvinces', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f7.svg', 'provinces', 'argentina-provinces', 'provinces-of-argentina', TRUE, FALSE, TRUE, TRUE),
(1, 8, 6, 'Australia', 'state or territory', 'States and Territories of Australia', 9, 300, 'AustraliaStatesAndTerritories', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1fa.svg', 'states and territories', 'australia-states-and-territories', 'states-and-territories-of-australia', TRUE, FALSE, TRUE, TRUE),
(1, 7, 5, 'Brazil', 'state', 'States of Brazil', 27, 300, 'BrazilStates', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f7.svg', 'states', 'brazil-states', 'states-of-brazil', TRUE, FALSE, TRUE, TRUE),
(1, 6, 4, 'Canada', 'province or territory', 'Provinces and Territories of Canada', 13, 300, 'CanadaProvincesAndTerritories', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1e6.svg', 'provinces and territories', 'canada-provinces-and-territories', 'provinces-and-territories-of-canada', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, 'China', 'administrative division', 'Administrative Divisions of China', 33, 300, 'ChinaAdministrativeDivisions', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f3.svg', 'administrative divisions', 'china-administrative-divisions', 'administrative-divisions-of-china', TRUE, FALSE, FALSE, TRUE),
(1, 7, 5, 'Colombia', 'department', 'Departments of Colombia', 33, 300, 'ColombiaDepartments', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f4.svg', 'departments', 'colombia-departments', 'departments-of-colombia', TRUE, FALSE, TRUE, TRUE),
(1, 5, 3, 'France', 'region', 'Regions of France', 13, 300, 'FranceRegions', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1f7.svg', 'regions', 'france-regions', 'regions-of-france', TRUE, FALSE, TRUE, TRUE),
(1, 5, 3, 'Germany', 'state', 'States of Germany', 16, 300, 'GermanyStates', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1ea.svg', 'states', 'germany-states', 'states-of-germany', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, 'India', 'state or union territory', 'States and Union Territories of India', 36, 300, 'IndiaStatesAndUnionTerritories', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f3.svg', 'states and union territories', 'india-states-and-union-territories', 'states-and-union-territories-of-india', TRUE, FALSE, FALSE, TRUE),
(1, 5, 3, 'Italy', 'region', 'Regions of Italy', 20, 300, 'ItalyRegions', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f9.svg', 'regions', 'italy-regions', 'regions-of-italy', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, 'Japan', 'prefecture', 'Prefectures of Japan', 47, 300, 'JapanPrefectures', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg', 'prefectures', 'japan-prefectures', 'prefectures-of-japan', TRUE, FALSE, TRUE, TRUE),
(1, 6, 4, 'Mexico', 'state', 'States of Mexico', 32, 300, 'MexicoStates', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fd.svg', 'states', 'mexico-states', 'states-of-mexico', TRUE, FALSE, FALSE, TRUE),
(1, 8, 6, 'New Zealand', 'region', 'Regions of New Zealand', 16, 300, 'NewZealandRegions', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ff.svg', 'regions', 'new-zealand-regions', 'regions-of-new-zealand', TRUE, FALSE, FALSE, TRUE),
(1, 3, 1, 'Nigeria', 'state', 'States of Nigeria', 37, 300, 'NigeriaStates', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ec.svg', 'states', 'nigeria-states', 'states-of-nigeria', TRUE, FALSE, FALSE, TRUE),
(1, 4, 2, 'Pakistan', 'administrative unit', 'Administrative Units of Pakistan', 8, 300, 'PakistanAdministrativeUnits', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1f0.svg', 'administrative units', 'pakistan-administrative-units', 'administrative-units-of-pakistan', TRUE, FALSE, FALSE, TRUE),
(1, 4, 2, 'Russia', 'federal subject', 'Federal Subjects of Russia', 83, 600, 'RussiaFederalSubjects', 'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg', 'federal subjects', 'russia-federal-subjects', 'federal-subjects-of-russia', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, 'South Korea', 'province', 'Provinces of South Korea', 17, 300, 'SouthKoreaProvinces', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg', 'provinces', 'south-korea-provinces', 'provinces-of-south-korea', TRUE, FALSE, TRUE, TRUE),
(1, 5, 3, 'Spain', 'province', 'Provinces of Spain', 52, 300, 'SpainProvinces', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1f8.svg', 'provinces', 'spain-provinces', 'provinces-of-spain', TRUE, FALSE, TRUE, TRUE),
(1, 4, 2, 'Turkey', 'province', 'Provinces of Turkey', 81, 600, 'TurkeyProvinces', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f7.svg', 'provinces', 'turkey-provinces', 'provinces-of-turkey', TRUE, FALSE, FALSE, TRUE),
(1, 3, 1, 'Uganda', 'district', 'Districts of Uganda', 112, 600, 'UgandaDistricts', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1ec.svg', 'districts', 'uganda-districts', 'districts-of-uganda', TRUE, FALSE, FALSE, TRUE),
(1, 5, 3, 'Ukraine', 'oblast', 'Oblasts of Ukraine', 25, 300, 'UkraineOblasts', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1e6.svg', 'oblasts', 'ukraine-oblasts', 'oblasts-of-ukraine', TRUE, FALSE, FALSE, TRUE),
(1, 5, 3, 'United Kingdom', 'country', 'Countries of the UK', 3, 300, 'UkCountries', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg', 'countries', 'uk-countries', 'countries-of-the-uk', FALSE, FALSE, TRUE, TRUE),
(1, 5, 3, 'United Kingdom', 'capital', 'Capitals of the UK', 3, 300, 'UkCapitals', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg', 'capitals', 'uk-capitals', 'capitals-of-the-uk', FALSE, FALSE, TRUE, TRUE),
(1, 5, 3, 'United Kingdom', 'sea', 'Seas of the UK', 4, 300, 'UkSeas', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg', 'seas', 'uk-seas', 'seas-of-the-uk', FALSE, FALSE, FALSE, TRUE),
(1, 5, 3, 'United Kingdom', 'county', 'Counties of the UK', 87, 900, 'UkCounties', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg', 'counties', 'uk-counties', 'counties-of-the-uk', TRUE, FALSE, FALSE, TRUE),
(1, 5, 3, 'United Kingdom', 'city', 'Major Cities of the UK', 106, 900, 'UkMajorCities', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg', 'cities', 'uk-major-cities', 'major-cities-of-the-uk', TRUE, FALSE, FALSE, TRUE),
(1, 6, 4, 'United States', 'state', 'US States', 50, 300, 'UsStates', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1f8.svg', 'states', 'us-states', 'us-states', TRUE, FALSE, TRUE, TRUE),
(1, 3, 1, 'Zambia', 'province', 'Provinces of Zambia', 10, 300, 'ZambiaProvinces', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ff-1f1f2.svg', 'provinces', 'zambia-provinces', 'provinces-of-zambia', TRUE, FALSE, FALSE, TRUE),
(2, 2, null, '', 'flag', 'Flags of the World', 197, 900, '', 'https://geobuff.sgp1.digitaloceanspaces.com/headers/world-map-header.svg', 'flags', 'world-countries', 'flags-of-the-world', TRUE, TRUE, TRUE, TRUE),
(2, 8, 6, 'Australia', 'flag', 'Flags of Australia', 8, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1fa.svg', 'flags', 'australia-states-and-territories-flags', 'flags-of-australia', TRUE, FALSE, TRUE, TRUE),
(2, 7, 5, 'Argentina', 'flag', 'Flags of Argentina', 24, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f7.svg', 'flags', 'argentina-provinces', 'flags-of-argentina', TRUE, FALSE, TRUE, TRUE),
(2, 7, 5, 'Brazil', 'flag', 'Flags of Brazil', 27, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f7.svg', 'flags', 'brazil-states', 'flags-of-brazil', TRUE, FALSE, TRUE, TRUE),
(2, 6, 4, 'Canada', 'flag', 'Flags of Canada', 13, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1e6.svg', 'flags', 'canada-provinces-and-territories', 'flags-of-canada', TRUE, FALSE, TRUE, TRUE),
(2, 7, 5, 'Colombia', 'flag' ,'Flags of Colombia', 33, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f4.svg', 'flags', 'colombia-departments', 'flags-of-colombia', TRUE, FALSE, TRUE, TRUE),
(2, 5, 3, 'France', 'flag', 'Flags of France', 13, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1f7.svg', 'flags', 'france-regions', 'flags-of-france', TRUE, FALSE, TRUE, TRUE),
(2, 5, 3, 'Germany', 'flag', 'Flags of Germany', 16, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1ea.svg', 'flags', 'germany-states', 'flags-of-germany', TRUE, FALSE, TRUE, TRUE),
(2, 5, 3, 'Italy', 'flag', 'Flags of Italy', 20, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f9.svg', 'flags', 'italy-regions', 'flags-of-italy', TRUE, FALSE, TRUE, TRUE),
(2, 4, 2, 'Japan', 'flag', 'Flags of Japan', 47, 300, '', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg', 'flags', 'japan-prefectures', 'flags-of-japan', TRUE, FALSE, TRUE, TRUE),
(2, 4, 2, 'Russia', 'flag', 'Flags of Russia', 83, 600, '', 'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg', 'flags', 'russia-federal-subjects', 'flags-of-russia', TRUE, FALSE, TRUE, TRUE),
(2, 4, 2, 'South Korea', 'flag', 'Flags of South Korea', 17, 300, '', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg', 'flags', 'south-korea-provinces', 'flags-of-south-korea', TRUE, FALSE, TRUE, TRUE),
(2, 5, 3, 'Spain', 'flag', 'Flags of Spain', 52, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1f8.svg', 'flags', 'spain-provinces', 'flags-of-spain', TRUE, FALSE, TRUE, TRUE),
(2, 5, 3, 'Ukraine', 'flag', 'Flags of Ukraine', 25, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1e6.svg', 'flags', 'ukraine-oblasts', 'flags-of-ukraine', TRUE, FALSE, TRUE, TRUE),
(2, 6, 4, 'United States', 'flag', 'Flags of the US', 50, 300, '', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1f8.svg', 'flags', 'us-states', 'flags-of-the-us', TRUE, FALSE, TRUE, TRUE);

INSERT INTO triviaQuestionType (name) values
('Text'),
('Image'),
('Flag'),
('Map');

INSERT INTO merch (name, description, sizeGuideImageUrl, price, externalLink, route) values
('Tee', 'With summer just around the corner, we teamed up with the only carbon neutral clothing company in New Zealand (Koa Goods) to bring you guys the freshest eco-friendly tee to let the squad know you''re ready to drop those countries of the world at a moments notice. By copping one of these OG pieces you''re directly contributing to hosting costs and helping us keep this thing afloat. Kia Kaha!', 'https://geobuff.sgp1.digitaloceanspaces.com/merch/tee/size-guide.png', 49.99, null, 'tee'),
('Socks', 'With summer just around the corner, we teamed up with the only carbon neutral clothing company in New Zealand (Koa Goods) to bring you guys the freshest eco-friendly hoof covers to let the squad know you don''t mess around when it comes to capital cities. By copping one of these OG pieces you''re directly contributing to hosting costs and helping us keep this thing afloat. Kia Kaha!', null, 11.99, null, 'socks'),
('Poster Combo', 'Just moved flats and the bedroom walls are looking bare, boring and barren? The folks at GeoBuff HQ have got you covered. We''ve teamed up with the goodfella''s at The Big Picture to spruce up that decor and let the homies know that when the flags come out, you mean business. By copping one of these OG pieces you''re directly contributing to hosting costs and helping us keep this thing afloat. Kia Kaha!', null, 29.99, null, 'poster-combo'),
('Sticker Pack', 'Rear window on the wagon covered in dust and Raglan Roast have run out of stickers? The folks at GeoBuff HQ have got you covered. We''ve teamed up with the goodfella''s at The Big Picture to spice up that rear window and let the geezers in the slow lane know that you get your geoflex on. By copping one of these OG pieces you''re directly contributing to hosting costs and helping us keep this thing afloat. Kia Kaha!', null, 24.99, null, 'sticker-pack');

INSERT INTO merchSizes (merchId, size, quantity) values
(1, 'S', 0),
(1, 'M', 0),
(1, 'L', 0),
(1, 'XL', 0),
(1, '2XL', 0),
(2, 'One Size Fits All', 0),
(3, 'A2', 0),
(4, 'A4', 0);

INSERT INTO merchImages (merchId, imageUrl, isPrimary) values
(1, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/tee/ash-front.jpg', TRUE),
(1, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/tee/pearl-front.jpg', FALSE),
(1, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/tee/dan-back.jpg', FALSE),
(1, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/tee/koa-label.jpg', FALSE),
(2, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/socks/holding.jpg', TRUE),
(2, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/socks/full-leg.jpg', FALSE),
(2, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/socks/close-up.jpg', FALSE),
(3, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/posters/combo.jpg', TRUE),
(3, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/posters/solo-green.jpg', FALSE),
(3, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/posters/solo-blue.jpg', FALSE),
(3, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/posters/mockup.png', FALSE),
(4, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/stickers/pack-flat.jpg', TRUE),
(4, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/stickers/pack-angle.jpg', FALSE),
(4, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/stickers/laptop.jpg', FALSE),
(4, 'https://geobuff.sgp1.digitaloceanspaces.com/merch/stickers/van.jpg', FALSE);

INSERT INTO discounts (merchId, code, amount) values
(null, 'NOSHIP', 5.99);

INSERT INTO orderStatus (status) values
('Pending'),
('Payment Received'),
('Shipped');

INSERT INTO shippingOptions (name, description, price, imageUrl) values
('NZ-Wide Standard Shipping', 'Expect delivery in 5-7 days', 5.99, 'https://upload.wikimedia.org/wikipedia/commons/1/1f/NZ_Post_logo.png');

INSERT INTO communityQuizStatus (name) values
('Pending'),
('Approved');

INSERT INTO triviaQuestionCategory (name) values
('Landmarks'),
('Currency'),
('Mountains'),
('Rivers'),
('Borders'),
('Community Quiz'),
('Misc'),
('Exports'),
('Sports');

INSERT INTO flagGroups (key, label) values
('world', '🌎 World, Countries'),
('au', '🇦🇺 Australia, States and Territories'),
('ar', '🇦🇷 Argentina, Provinces'),
('br', '🇧🇷 Brazil, States'),
('ca', '🇨🇦 Canada, Provinces and Territories'),
('co', '🇨🇴 Colombia, Departments'),
('fr', '🇫🇷 France, Regions'),
('de', '🇩🇪 Germany, States'),
('gb', '🇬🇧 Great Britain, Countries'),
('it', '🇮🇹 Italy, Regions'),
('jp', '🇯🇵 Japan, Prefectures'),
('ru', '🇷🇺 Russia, Federal Subjects'),
('kr', '🇰🇷 South Korea, Provinces'),
('es', '🇪🇸 Spain, Provinces'),
('ua', '🇺🇦 Ukraine, Oblasts'),
('us', '🇺🇸 US, States');

INSERT INTO flagEntries (groupId, code, url) values
(1, 'buff', 'https://ik.imagekit.io/ucszu5sud3vz/flag-geobuff-sm'),
(1, 'ad', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1e9.svg'),
(1, 'ae', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1ea.svg'),
(1, 'af', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1eb.svg'),
(1, 'ag', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1ec.svg'),
(1, 'al', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f1.svg'),
(1, 'am', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f2.svg'),
(1, 'ao', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f4.svg'),
(1, 'ar', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f7.svg'),
(1, 'at', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1f9.svg'),
(1, 'au', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1fa.svg'),
(1, 'az', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1ff.svg'),
(1, 'ba', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1e6.svg'),
(1, 'bb', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1e7.svg'),
(1, 'bd', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1e9.svg'),
(1, 'be', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ea.svg'),
(1, 'bf', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1eb.svg'),
(1, 'bg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ec.svg'),
(1, 'bh', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ed.svg'),
(1, 'bi', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ee.svg'),
(1, 'bj', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ef.svg'),
(1, 'bn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f3.svg'),
(1, 'bo', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f4.svg'),
(1, 'br', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f7.svg'),
(1, 'bs', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f8.svg'),
(1, 'bt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1f9.svg'),
(1, 'bw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1fc.svg'),
(1, 'by', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1fe.svg'),
(1, 'bz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e7-1f1ff.svg'),
(1, 'ca', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1e6.svg'),
(1, 'cd', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1e9.svg'),
(1, 'cf', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1eb.svg'),
(1, 'cg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1ec.svg'),
(1, 'ch', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1ed.svg'),
(1, 'ci', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1ee.svg'),
(1, 'cl', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f1.svg'),
(1, 'cm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f2.svg'),
(1, 'cn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f3.svg'),
(1, 'co', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f4.svg'),
(1, 'cr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1f7.svg'),
(1, 'cu', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1fa.svg'),
(1, 'cv', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1fb.svg'),
(1, 'cy', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1fe.svg'),
(1, 'cz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e8-1f1ff.svg'),
(1, 'de', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1ea.svg'),
(1, 'dj', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1ef.svg'),
(1, 'dk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1f0.svg'),
(1, 'dm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1f2.svg'),
(1, 'do', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1f4.svg'),
(1, 'dz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e9-1f1ff.svg'),
(1, 'ec', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1e8.svg'),
(1, 'ee', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1ea.svg'),
(1, 'eg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1ec.svg'),
(1, 'er', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1f7.svg'),
(1, 'es', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1f8.svg'),
(1, 'et', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ea-1f1f9.svg'),
(1, 'fi', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1ee.svg'),
(1, 'fj', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1ef.svg'),
(1, 'fm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1f2.svg'),
(1, 'fr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1eb-1f1f7.svg'),
(1, 'ga', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e6.svg'),
(1, 'gb', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e7.svg'),
(1, 'gd', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1e9.svg'),
(1, 'ge', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1ea.svg'),
(1, 'gh', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1ed.svg'),
(1, 'gm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1f2.svg'),
(1, 'gn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1f3.svg'),
(1, 'gq', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1f6.svg'),
(1, 'gr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1f7.svg'),
(1, 'gt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1f9.svg'),
(1, 'gw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1fc.svg'),
(1, 'gy', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ec-1f1fe.svg'),
(1, 'hn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ed-1f1f3.svg'),
(1, 'hr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ed-1f1f7.svg'),
(1, 'ht', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ed-1f1f9.svg'),
(1, 'hu', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ed-1f1fa.svg'),
(1, 'id', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1e9.svg'),
(1, 'ie', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1ea.svg'),
(1, 'il', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f1.svg'),
(1, 'in', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f3.svg'),
(1, 'iq', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f6.svg'),
(1, 'ir', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f7.svg'),
(1, 'is', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f8.svg'),
(1, 'it', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ee-1f1f9.svg'),
(1, 'jm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ef-1f1f2.svg'),
(1, 'jo', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ef-1f1f4.svg'),
(1, 'jp', 'https://ik.imagekit.io/ucszu5sud3vz/flag-jp_9E4mwVsqHDW.svg'),
(1, 'ke', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1ea.svg'),
(1, 'kg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1ec.svg'),
(1, 'kh', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1ed.svg'),
(1, 'ki', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1ee.svg'),
(1, 'km', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1f2.svg'),
(1, 'kn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1f3.svg'),
(1, 'kp', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1f5.svg'),
(1, 'kr', 'https://ik.imagekit.io/ucszu5sud3vz/flag-kr_tYV56l4dBQ3.svg'),
(1, 'kw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1fc.svg'),
(1, 'kz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f0-1f1ff.svg'),
(1, 'la', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1e6.svg'),
(1, 'lb', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1e7.svg'),
(1, 'lc', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1e8.svg'),
(1, 'li', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1ee.svg'),
(1, 'lk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1f0.svg'),
(1, 'lr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1f7.svg'),
(1, 'ls', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1f8.svg'),
(1, 'lt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1f9.svg'),
(1, 'lu', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1fa.svg'),
(1, 'lv', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1fb.svg'),
(1, 'ly', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f1-1f1fe.svg'),
(1, 'ma', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1e6.svg'),
(1, 'mc', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1e8.svg'),
(1, 'md', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1e9.svg'),
(1, 'me', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1ea.svg'),
(1, 'mg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1ec.svg'),
(1, 'mh', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1ed.svg'),
(1, 'mk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f0.svg'),
(1, 'ml', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f1.svg'),
(1, 'mm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f2.svg'),
(1, 'mn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f3.svg'),
(1, 'mr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f7.svg'),
(1, 'mt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1f9.svg'),
(1, 'mu', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fa.svg'),
(1, 'mv', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fb.svg'),
(1, 'mw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fc.svg'),
(1, 'mx', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fd.svg'),
(1, 'my', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1fe.svg'),
(1, 'mz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f2-1f1ff.svg'),
(1, 'na', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1e6.svg'),
(1, 'ne', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ea.svg'),
(1, 'ng', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ec.svg'),
(1, 'ni', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ee.svg'),
(1, 'nl', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1f1.svg'),
(1, 'no', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1f4.svg'),
(1, 'np', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1f5.svg'),
(1, 'nr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1f7.svg'),
(1, 'nz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f3-1f1ff.svg'),
(1, 'om', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f4-1f1f2.svg'),
(1, 'pa', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1e6.svg'),
(1, 'pe', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1ea.svg'),
(1, 'pg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1ec.svg'),
(1, 'ph', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1ed.svg'),
(1, 'pk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1f0.svg'),
(1, 'pl', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1f1.svg'),
(1, 'ps', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1f8.svg'),
(1, 'pt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1f9.svg'),
(1, 'pw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1fc.svg'),
(1, 'py', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f5-1f1fe.svg'),
(1, 'qa', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f6-1f1e6.svg'),
(1, 'ro', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f7-1f1f4.svg'),
(1, 'rs', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f7-1f1f8.svg'),
(1, 'ru', 'https://ik.imagekit.io/ucszu5sud3vz/flag-ru_hI7yCCaMi7E.svg'),
(1, 'rw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f7-1f1fc.svg'),
(1, 'sa', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1e6.svg'),
(1, 'sb', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1e7.svg'),
(1, 'sc', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1e8.svg'),
(1, 'sd', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1e9.svg'),
(1, 'se', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1ea.svg'),
(1, 'sg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1ec.svg'),
(1, 'si', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1ee.svg'),
(1, 'sk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f0.svg'),
(1, 'sl', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f1.svg'),
(1, 'sm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f2.svg'),
(1, 'sn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f3.svg'),
(1, 'so', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f4.svg'),
(1, 'sr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f7.svg'),
(1, 'ss', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f8.svg'),
(1, 'st', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1f9.svg'),
(1, 'sv', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1fb.svg'),
(1, 'sy', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1fe.svg'),
(1, 'sz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f8-1f1ff.svg'),
(1, 'td', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1e9.svg'),
(1, 'tg', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1ec.svg'),
(1, 'th', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1ed.svg'),
(1, 'tj', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1ef.svg'),
(1, 'tl', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f1.svg'),
(1, 'tm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f2.svg'),
(1, 'tn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f3.svg'),
(1, 'to', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f4.svg'),
(1, 'tr', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f7.svg'),
(1, 'tt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1f9.svg'),
(1, 'tv', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1fb.svg'),
(1, 'tw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1fc.svg'),
(1, 'tz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1f9-1f1ff.svg'),
(1, 'ua', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1e6.svg'),
(1, 'ug', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1ec.svg'),
(1, 'us', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1f8.svg'),
(1, 'uy', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1fe.svg'),
(1, 'uz', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fa-1f1ff.svg'),
(1, 'va', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fb-1f1e6.svg'),
(1, 'vc', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fb-1f1e8.svg'),
(1, 've', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fb-1f1ea.svg'),
(1, 'vn', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fb-1f1f3.svg'),
(1, 'vu', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fb-1f1fa.svg'),
(1, 'ws', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fc-1f1f8.svg'),
(1, 'xk', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fd-1f1f0.svg'),
(1, 'ye', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1fe-1f1ea.svg'),
(1, 'za', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ff-1f1e6.svg'),
(1, 'zm', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ff-1f1f2.svg'),
(1, 'zw', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1ff-1f1fc.svg'),
(2, 'au-nsw', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_New_South_Wales.svg'),
(2, 'au-qld', 'https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Queensland.svg'),
(2, 'au-sa', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_South_Australia.svg'),
(2, 'au-tas', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Tasmania.svg'),
(2, 'au-vic', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Victoria_%28Australia%29.svg'),
(2, 'au-wa', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Flag_of_Western_Australia.svg'),
(2, 'au-act', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_the_Australian_Capital_Territory.svg'),
(2, 'au-jbt', 'https://twemoji.maxcdn.com/v/13.0.1/svg/1f1e6-1f1fa.svg'),
(2, 'au-nt', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_the_Northern_Territory.svg'),
(3, 'ar-ba', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Bandera_de_la_Provincia_de_Buenos_Aires.svg'),
(3, 'ar-ct', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Bandera_de_la_Provincia_de_Catamarca.svg'),
(3, 'ar-cc', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Bandera_de_la_Provincia_del_Chaco.svg'),
(3, 'ar-ch', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Bandera_de_la_Provincia_del_Chubut.svg'),
(3, 'ar-df', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Bandera_de_la_Ciudad_de_Buenos_Aires.svg'),
(3, 'ar-cb', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Bandera_de_la_Provincia_de_C%C3%B3rdoba.svg'),
(3, 'ar-cn', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Bandera_de_la_Provincia_de_Corrientes.svg'),
(3, 'ar-er', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bandera_de_la_Provincia_de_Entre_R%C3%ADos.svg'),
(3, 'ar-fm', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Bandera_de_la_Provincia_de_Formosa.svg'),
(3, 'ar-jy', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Bandera_de_la_Provincia_de_Jujuy.svg'),
(3, 'ar-lp', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Bandera_de_la_Provincia_de_La_Pampa.svg'),
(3, 'ar-lr', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Bandera_de_la_Provincia_de_La_Rioja.svg'),
(3, 'ar-mz', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Bandera_de_la_Provincia_de_Mendoza.svg'),
(3, 'ar-mn', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Bandera_de_la_Provincia_de_Misiones.svg'),
(3, 'ar-nq', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Bandera_de_la_Provincia_de_Neuqu%C3%A9n.svg'),
(3, 'ar-rn', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Bandera_de_la_Provincia_del_R%C3%ADo_Negro.svg'),
(3, 'ar-sa', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Bandera_de_la_Provincia_de_Salta.svg'),
(3, 'ar-sj', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Bandera_de_San_Juan_Ciudadana.png'),
(3, 'ar-sl', 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Bandera_de_la_Provincia_de_San_Luis.svg'),
(3, 'ar-sc', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Bandera_de_la_Provincia_de_Santa_Cruz.svg'),
(3, 'ar-sf', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Bandera_de_la_Provincia_de_Santa_Fe.svg'),
(3, 'ar-se', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Bandera_de_la_Provincia_de_Santiago_del_Estero.svg'),
(3, 'ar-tf', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Bandera_de_la_Provincia_de_Tierra_del_Fuego.svg'),
(3, 'ar-tm', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Bandera_de_la_Provincia_de_Tucum%C3%A1n.svg'),
(4, 'br-am', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Bandeira_do_Amazonas.svg'),
(4, 'br-pa', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Bandeira_do_Par%C3%A1.svg'),
(4, 'br-mt', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Bandeira_de_Mato_Grosso.svg'),
(4, 'br-mg', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Bandeira_de_Minas_Gerais.svg'),
(4, 'br-ba', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Bandeira_da_Bahia.svg'),
(4, 'br-ms', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Bandeira_de_Mato_Grosso_do_Sul.svg'),
(4, 'br-go', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_Goi%C3%A1s.svg'),
(4, 'br-ma', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Bandeira_do_Maranh%C3%A3o.svg'),
(4, 'br-rs', 'https://upload.wikimedia.org/wikipedia/commons/6/63/Bandeira_do_Rio_Grande_do_Sul.svg'),
(4, 'br-to', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Bandeira_do_Tocantins.svg'),
(4, 'br-pi', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Bandeira_do_Piau%C3%AD.svg'),
(4, 'br-sp', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Bandeira_do_estado_de_S%C3%A3o_Paulo.svg'),
(4, 'br-ro', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Bandeira_de_Rond%C3%B4nia.svg'),
(4, 'br-rr', 'https://upload.wikimedia.org/wikipedia/commons/9/98/Bandeira_de_Roraima.svg'),
(4, 'br-pr', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Bandeira_do_Paran%C3%A1.svg'),
(4, 'br-ac', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Bandeira_do_Acre.svg'),
(4, 'br-ce', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Bandeira_do_Cear%C3%A1.svg'),
(4, 'br-ap', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Bandeira_do_Amap%C3%A1.svg'),
(4, 'br-pe', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Bandeira_de_Pernambuco.svg'),
(4, 'br-sc', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Bandeira_de_Santa_Catarina.svg'),
(4, 'br-pb', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Bandeira_da_Para%C3%ADba.svg'),
(4, 'br-rn', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Bandeira_do_Rio_Grande_do_Norte.svg'),
(4, 'br-es', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Bandeira_do_Esp%C3%ADrito_Santo.svg'),
(4, 'br-rj', 'https://upload.wikimedia.org/wikipedia/commons/7/73/Bandeira_do_estado_do_Rio_de_Janeiro.svg'),
(4, 'br-al', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Bandeira_de_Alagoas.svg'),
(4, 'br-se', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Bandeira_de_Sergipe.svg'),
(4, 'br-df', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Bandeira_do_Distrito_Federal_%28Brasil%29.svg'),
(5, 'ca-nu', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Flag_of_Nunavut.svg'),
(5, 'ca-qc', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_Quebec.svg'),
(5, 'ca-nt', 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_the_Northwest_Territories.svg'),
(5, 'ca-on', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Ontario.svg'),
(5, 'ca-bc', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_British_Columbia.svg'),
(5, 'ca-ab', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Flag_of_Alberta.svg'),
(5, 'ca-sk', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_Saskatchewan.svg'),
(5, 'ca-mb', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Manitoba.svg'),
(5, 'ca-yt', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Yukon.svg'),
(5, 'ca-nl', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Newfoundland_and_Labrador.svg'),
(5, 'ca-nb', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_New_Brunswick.svg'),
(5, 'ca-ns', 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Nova_Scotia.svg'),
(5, 'ca-pe', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Flag_of_Prince_Edward_Island.svg'),
(6, 'co-ama', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Amazonas_%28Colombia%29.svg'),
(6, 'co-ant', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Flag_of_Antioquia_Department.svg'),
(6, 'co-ara', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_of_Arauca.svg'),
(6, 'co-atl', 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Flag_of_Atl%C3%A1ntico.svg'),
(6, 'co-bol', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Bol%C3%ADvar_%28Colombia%29.svg'),
(6, 'co-boy', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_Boyac%C3%A1_Department.svg'),
(6, 'co-cau', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_Cauca.svg'),
(6, 'co-ces', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Cesar.svg'),
(6, 'co-cho', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_Choc%C3%B3.svg'),
(6, 'co-cal', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Flag_of_Caldas.svg'),
(6, 'co-cor', 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_C%C3%B3rdoba.svg'),
(6, 'co-caq', 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Flag_of_Caquet%C3%A1.svg'),
(6, 'co-cas', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Casanare.svg'),
(6, 'co-cun', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Cundinamarca.svg'),
(6, 'co-dc', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Bogot%C3%A1.svg'),
(6, 'co-gua', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Guain%C3%ADa.svg'),
(6, 'co-guv', 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Guaviare.svg'),
(6, 'co-hui', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Flag_of_Huila.svg'),
(6, 'co-lag', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_La_Guajira.svg'),
(6, 'co-mag', 'https://upload.wikimedia.org/wikipedia/commons/1/18/Flag_of_Magdalena.svg'),
(6, 'co-met', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_Meta.svg'),
(6, 'co-nar', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_Nari%C3%B1o.svg'),
(6, 'co-nsa', 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Norte_de_Santander.svg'),
(6, 'co-put', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_Putumayo.svg'),
(6, 'co-qui', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Quind%C3%ADo.svg'),
(6, 'co-ris', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Risaralda.svg'),
(6, 'co-san', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_Santander_%28Colombia%29.svg'),
(6, 'co-suc', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Flag_of_Sucre_%28Colombia%29.svg'),
(6, 'co-sap', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_San_Andr%C3%A9s_y_Providencia.svg'),
(6, 'co-tol', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Tolima.svg'),
(6, 'co-vac', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Valle_del_Cauca.svg'),
(6, 'co-vid', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Vichada.svg'),
(6, 'co-vau', 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Vaup%C3%A9s.svg'),
(7, 'fr-ar', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_the_region_Auvergne-Rh%C3%B4ne-Alpes.svg'),
(7, 'fr-bf', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_the_region_Bourgogne-Franche-Comt%C3%A9.svg'),
(7, 'fr-bt', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Brittany_%28Gwenn_ha_du%29.svg'),
(7, 'fr-cn', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Flag_of_Centre-Val_de_Loire.svg'),
(7, 'fr-ce', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Flag_of_Corsica.svg'),
(7, 'fr-ao', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Proposed_design_for_a_flag_of_Grand_Est.svg'),
(7, 'fr-nc', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Proposed_design_for_a_flag_of_Hauts-de-France.svg'),
(7, 'fr-if', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Proposed_flag_of_%C3%8Ele-de-France.svg'),
(7, 'fr-nd', 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Normandie.svg'),
(7, 'fr-ac', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Flag_of_Nouvelle-Aquitaine.svg'),
(7, 'fr-lp', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Flag_of_R%C3%A9gion_Occitanie_%28symbol_only%29.svg'),
(7, 'fr-pl', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Unofficial_flag_of_Pays-de-la-Loire.svg'),
(7, 'fr-pr', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_Provence-Alpes-C%C3%B4te_d%27Azur.svg'),
(8, 'de-bw', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Baden-W%C3%BCrttemberg.svg'),
(8, 'de-by', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Flag_of_Bavaria_%28striped%29.svg'),
(8, 'de-be', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Berlin.svg'),
(8, 'de-bb', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Brandenburg.svg'),
(8, 'de-hb', 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Flag_of_Bremen.svg'),
(8, 'de-hh', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Hamburg.svg'),
(8, 'de-he', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Hesse.svg'),
(8, 'de-ni', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Flag_of_Lower_Saxony.svg'),
(8, 'de-mv', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Mecklenburg-Western_Pomerania.svg'),
(8, 'de-nw', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_North_Rhine-Westphalia.svg'),
(8, 'de-rp', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Rhineland-Palatinate.svg'),
(8, 'de-sl', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Saarland.svg'),
(8, 'de-sn', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Saxony.svg'),
(8, 'de-st', 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Flag_of_Saxony-Anhalt_%28state%29.svg'),
(8, 'de-sh', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Schleswig-Holstein.svg'),
(8, 'de-th', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Thuringia.svg'),
(9, 'gb-eng', 'https://upload.wikimedia.org/wikipedia/en/b/be/Flag_of_England.svg'),
(9, 'gb-sct', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg'),
(9, 'gb-wls', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Flag_of_Wales.svg'),
(10, 'it-65', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Abruzzo.svg'),
(10, 'it-77', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Flag_of_Basilicata.svg'),
(10, 'it-78', 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Flag_of_Calabria.svg'),
(10, 'it-72', 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Flag_of_Campania.svg'),
(10, 'it-45', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Emilia-Romagna_%28de_facto%29.svg'),
(10, 'it-36', 'https://upload.wikimedia.org/wikipedia/commons/5/55/Flag_of_Friuli-Venezia_Giulia.svg'),
(10, 'it-62', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Flag_of_Lazio.svg'),
(10, 'it-42', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Liguria.svg'),
(10, 'it-25', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Lombardy.svg'),
(10, 'it-57', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Marche.svg'),
(10, 'it-67', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Molise.svg'),
(10, 'it-21', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Piedmont.svg'),
(10, 'it-75', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Apulia.svg'),
(10, 'it-88', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Sardinia%2C_Italy.svg'),
(10, 'it-82', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Sicilian_Flag.svg'),
(10, 'it-52', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Tuscany.svg'),
(10, 'it-32', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_South_Tyrol.svg'),
(10, 'it-55', 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Flag_of_Umbria.svg'),
(10, 'it-23', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Flag_of_Valle_d%27Aosta.svg'),
(10, 'it-34', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Flag_of_Veneto.svg'),
(11, 'jp-01', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Hokkaido_Prefecture.svg'),
(11, 'jp-02', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Aomori_Prefecture.svg'),
(11, 'jp-03', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Iwate_Prefecture.svg'),
(11, 'jp-04', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Miyagi_Prefecture.svg'),
(11, 'jp-05', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Akita_Prefecture.svg'),
(11, 'jp-06', 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Flag_of_Yamagata_Prefecture.svg'),
(11, 'jp-07', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Fukushima_Prefecture.svg'),
(11, 'jp-08', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Flag_of_Ibaraki_Prefecture.svg'),
(11, 'jp-09', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Flag_of_Tochigi_Prefecture.svg'),
(11, 'jp-10', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Gunma_Prefecture.svg'),
(11, 'jp-11', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Saitama_Prefecture.svg'),
(11, 'jp-12', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Chiba_Prefecture.svg'),
(11, 'jp-13', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Flag_of_Tokyo_Metropolis.svg'),
(11, 'jp-14', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_Kanagawa_Prefecture.svg'),
(11, 'jp-15', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Niigata_Prefecture.svg'),
(11, 'jp-16', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Flag_of_Toyama_Prefecture.svg'),
(11, 'jp-17', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Ishikawa_Prefecture.svg'),
(11, 'jp-18', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Fukui_Prefecture.svg'),
(11, 'jp-19', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Yamanashi_Prefecture.svg'),
(11, 'jp-20', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Nagano_Prefecture.svg'),
(11, 'jp-21', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Gifu_Prefecture.svg'),
(11, 'jp-22', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Shizuoka_Prefecture.svg'),
(11, 'jp-23', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Aichi_Prefecture.svg'),
(11, 'jp-24', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Mie_Prefecture.svg'),
(11, 'jp-25', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Shiga_Prefecture.svg'),
(11, 'jp-26', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Kyoto_Prefecture.svg'),
(11, 'jp-27', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Osaka_Prefecture.svg'),
(11, 'jp-28', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Hyogo_Prefecture.svg'),
(11, 'jp-29', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Nara_Prefecture.svg'),
(11, 'jp-30', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Wakayama_Prefecture.svg'),
(11, 'jp-31', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_Tottori_Prefecture.svg'),
(11, 'jp-32', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Shimane_Prefecture.svg'),
(11, 'jp-33', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Flag_of_Okayama_Prefecture.svg'),
(11, 'jp-34', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Hiroshima_Prefecture.svg'),
(11, 'jp-35', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Yamaguchi_Prefecture.svg'),
(11, 'jp-36', 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Tokushima_Prefecture.svg'),
(11, 'jp-37', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Kagawa_Prefecture.svg'),
(11, 'jp-38', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Flag_of_Ehime_Prefecture.svg'),
(11, 'jp-39', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Kochi_Prefecture.svg'),
(11, 'jp-40', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Fukuoka_Prefecture.svg'),
(11, 'jp-41', 'https://upload.wikimedia.org/wikipedia/commons/1/18/Flag_of_Saga_Prefecture.svg'),
(11, 'jp-42', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Nagasaki_Prefecture.svg'),
(11, 'jp-43', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Kumamoto_Prefecture.svg'),
(11, 'jp-44', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Flag_of_Oita_Prefecture.svg'),
(11, 'jp-45', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Flag_of_Miyazaki_Prefecture.svg'),
(11, 'jp-46', 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Flag_of_Kagoshima_Prefecture.svg'),
(11, 'jp-47', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Okinawa_Prefecture.svg'),
(12, 'ru-ad', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Flag_of_Adygea.svg'),
(12, 'ru-alt', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Altai_Republic.svg'),
(12, 'ru-amu', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_Amur_Oblast.svg'),
(12, 'ru-ark', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Flag_of_Arkhangelsk_Oblast.svg'),
(12, 'ru-ast', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_Astrakhan_Oblast.svg'),
(12, 'ru-ba', 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Flag_of_Bashkortostan.svg'),
(12, 'ru-bel', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Flag_of_Belgorod_Oblast.svg'),
(12, 'ru-bry', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Flag_of_Bryansk_Oblast.svg'),
(12, 'ru-bu', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Buryatia.svg'),
(12, 'ru-ce', 'https://upload.wikimedia.org/wikipedia/commons/1/13/Flag_of_the_Chechen_Republic.svg'),
(12, 'ru-che', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Chelyabinsk_Oblast.svg'),
(12, 'ru-chu', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Chukotka.svg'),
(12, 'ru-cu', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Flag_of_Chuvashia.svg'),
(12, 'ru-da', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_Dagestan.svg'),
(12, 'ru-al', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Altai_Republic.svg'),
(12, 'ru-in', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Ingushetia.svg'),
(12, 'ru-irk', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Flag_of_Irkutsk_Oblast.svg'),
(12, 'ru-iva', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Ivanovo_Oblast.svg'),
(12, 'ru-kb', 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Flag_of_Kabardino-Balkaria.svg'),
(12, 'ru-kc', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Karachay-Cherkessia.svg'),
(12, 'ru-kda', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_Krasnodar_Krai.svg'),
(12, 'ru-kem', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Kemerovo_oblast.svg'),
(12, 'ru-klu', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Kaluga_Oblast.svg'),
(12, 'ru-kha', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Khabarovsk_%28Khabarovsk_kray%29.png'),
(12, 'ru-kr', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Karelia.svg'),
(12, 'ru-kk', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Khakassia.svg'),
(12, 'ru-kl', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Kalmykia.svg'),
(12, 'ru-khm', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Flag_of_Yugra.svg'),
(12, 'ru-kgd', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_Kaliningrad_Oblast.svg'),
(12, 'ru-ko', 'https://en.wikipedia.org/wiki/Komi_Republic#/media/File:Flag_of_Komi.svg'),
(12, 'ru-kam', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_Kamchatka_Krai.svg'),
(12, 'ru-krs', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Flag_of_Kursk_Oblast.svg'),
(12, 'ru-kos', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Kostroma_Oblast.svg'),
(12, 'ru-kgn', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Kurgan_Oblast.svg'),
(12, 'ru-kir', 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Kirov_Oblast.svg'),
(12, 'ru-kya', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Flag_of_Krasnoyarsk_Krai.svg'),
(12, 'ru-len', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Leningrad_Oblast.svg'),
(12, 'ru-lip', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Lipetsk_Oblast.svg'),
(12, 'ru-mow', 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Moscow%2C_Russia.svg'),
(12, 'ru-me', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_Mari_El.svg'),
(12, 'ru-mag', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Magadan_Oblast.svg'),
(12, 'ru-mur', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Flag_of_Murmansk_Oblast.svg'),
(12, 'ru-mo', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Mordovia.svg'),
(12, 'ru-mos', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Moscow_oblast.svg'),
(12, 'ru-ngr', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Novgorod_Oblast.svg'),
(12, 'ru-nen', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Flag_of_Nenets_Autonomous_District.svg'),
(12, 'ru-se', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_North_Ossetia.svg'),
(12, 'ru-nvs', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Flag_of_Novosibirsk_oblast.svg'),
(12, 'ru-niz', 'https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Nizhny_Novgorod_Region.svg'),
(12, 'ru-ore', 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Flag_of_Orenburg_Oblast.svg'),
(12, 'ru-orl', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Oryol_Oblast.svg'),
(12, 'ru-oms', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Omsk_Oblast.svg'),
(12, 'ru-per', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Perm_Krai.svg'),
(12, 'ru-pri', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Primorsky_Krai.svg'),
(12, 'ru-psk', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Pskov_Oblast.svg'),
(12, 'ru-pnz', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Penza_Oblast.svg'),
(12, 'ru-ros', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Rostov_Oblast.svg'),
(12, 'ru-rya', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Ryazan_Oblast.svg'),
(12, 'ru-sam', 'https://upload.wikimedia.org/wikipedia/commons/1/13/Flag_of_Samara_Oblast.svg'),
(12, 'ru-sa', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Flag_of_Sakha.svg'),
(12, 'ru-sak', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Flag_of_Sakhalin_Oblast.svg'),
(12, 'ru-smo', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Smolensk_oblast.svg'),
(12, 'ru-spe', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Saint_Petersburg.svg'),
(12, 'ru-sar', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Flag_of_Saratov_Oblast.svg'),
(12, 'ru-sta', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Stavropol_Krai.svg'),
(12, 'ru-sve', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Sverdlovsk_Oblast.svg'),
(12, 'ru-tam', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Flag_of_Tambov_Oblast.svg'),
(12, 'ru-tom', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Tomsk_Oblast.svg'),
(12, 'ru-tul', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Tula_Oblast.svg'),
(12, 'ru-ta', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Tatarstan.svg'),
(12, 'ru-ty', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Tuva.svg'),
(12, 'ru-tve', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Tver_Oblast.svg'),
(12, 'ru-tyu', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Tyumen_Oblast.svg'),
(12, 'ru-ud', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Udmurtia.svg'),
(12, 'ru-uly', 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Flag_of_Ulyanovsk_Oblast.svg'),
(12, 'ru-vgg', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Volgograd_Oblast.svg'),
(12, 'ru-vla', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Vladimirskaya_Oblast.svg'),
(12, 'ru-yan', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Yamal-Nenets_Autonomous_District.svg'),
(12, 'ru-vlg', 'https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_Vologda_oblast.svg'),
(12, 'ru-vor', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Voronezh_Oblast.svg'),
(12, 'ru-yar', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Yaroslavl_Oblast.svg'),
(12, 'ru-yev', 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Flag_of_the_Jewish_Autonomous_Oblast.svg'),
(12, 'ru-zab', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Zabaykalsky_Krai.svg'),
(13, 'kr-11', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Seoul.svg'),
(13, 'kr-26', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_Busan.svg'),
(13, 'kr-27', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Daegu.svg'),
(13, 'kr-28', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Flag_of_Incheon.svg'),
(13, 'kr-29', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Gwangju.svg'),
(13, 'kr-30', 'https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Daejeon.svg'),
(13, 'kr-31', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Ulsan.svg'),
(13, 'kr-41', 'https://upload.wikimedia.org/wikipedia/commons/8/80/Flag_of_Gyeonggi_Province_%282021%29.svg'),
(13, 'kr-42', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Gangwon_Province.svg'),
(13, 'kr-43', 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Flag_of_North_Chungcheong_Province.svg'),
(13, 'kr-44', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_South_Chungcheong_Province.svg'),
(13, 'kr-45', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Flag_of_North_Jeolla_Province.svg'),
(13, 'kr-46', 'https://upload.wikimedia.org/wikipedia/commons/5/58/Flag_of_South_Jeolla_Province.svg'),
(13, 'kr-47', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_North_Gyeongsang_Province.svg'),
(13, 'kr-48', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_South_Gyeongsang_Province.svg'),
(13, 'kr-49', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Jeju.svg'),
(13, 'kr-50', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Sejong_City%2C_South_Korea.svg'),
(14, 'es-a', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Escut_de_la_Prov%C3%ADncia_d%27Alacant.svg'),
(14, 'es-ab', 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Bandera_provincia_Albacete.svg'),
(14, 'es-al', 'https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_Almer%C3%ADa_Province.svg'),
(14, 'es-av', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Bandera_de_la_provincia_de_%C3%81vila.svg'),
(14, 'es-b', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Barcelona_province%28official%29.svg'),
(14, 'es-ba', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Provincia_de_Badajoz_-_Bandera.svg'),
(14, 'es-bi', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Bandera_de_Vizcaya.svg'),
(14, 'es-bu', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_Burgos_Province.svg'),
(14, 'es-c', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Coat_of_Arms_of_the_Province_of_Corunna.svg'),
(14, 'es-ca', 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Flag_C%C3%A1diz_Province.svg'),
(14, 'es-cc', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Flag_of_the_province_of_C%C3%A1ceres.svg'),
(14, 'es-ce', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_Ceuta.svg'),
(14, 'es-co', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Provincia_de_C%C3%B3rdoba_-_Bandera.svg'),
(14, 'es-cr', 'https://upload.wikimedia.org/wikipedia/commons/3/37/Flag_Ciudad_Real_Province.svg'),
(14, 'es-cs', 'https://upload.wikimedia.org/wikipedia/commons/7/79/Escut_de_la_Prov%C3%ADncia_de_Castell%C3%B3.svg'),
(14, 'es-cu', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_Cuenca_Province.svg'),
(14, 'es-gc', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Bandera_Provincial_de_Las_Palmas.svg'),
(14, 'es-gi', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Girona_province_%28unofficial%29.svg'),
(14, 'es-gr', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Bandera_de_la_provincia_de_Granada_%28Espa%C3%B1a%29.svg'),
(14, 'es-gu', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_Guadalajara_Province.svg'),
(14, 'es-h', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Bandera_de_la_Provincia_De_Huelva.svg'),
(14, 'es-hu', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Huesca_%28province%29.svg'),
(14, 'es-j', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Bandera_de_la_provincia_de_Ja%C3%A9n.svg'),
(14, 'es-l', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Bandera_de_la_provincia_de_L%C3%A9rida.svg'),
(14, 'es-le', 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Bandera_de_Le%C3%B3n.svg'),
(14, 'es-lo', 'https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_La_Rioja_%28with_coat_of_arms%29.svg'),
(14, 'es-lu', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Lugo_province.svg'),
(14, 'es-m', 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_the_Community_of_Madrid.svg'),
(14, 'es-ma', 'https://upload.wikimedia.org/wikipedia/commons/2/21/Bandera_Provincia_de_M%C3%A1laga.jpg'),
(14, 'es-ml', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Melilla.svg'),
(14, 'es-mu', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Flag_of_the_Region_of_Murcia.svg'),
(14, 'es-na', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Bandera_de_Navarra.svg'),
(14, 'es-o', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Asturias.svg'),
(14, 'es-or', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Provincia_de_Ourense_-_Bandera.svg'),
(14, 'es-p', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Bandera_de_la_provincia_de_Palencia.svg'),
(14, 'es-pm', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Flag_of_the_Balearic_Islands.svg'),
(14, 'es-po', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_Pontevedra_Province.svg'),
(14, 'es-s', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Cantabria_%28Official%29.svg'),
(14, 'es-sa', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Bandera_de_la_provincia_de_Salamanca.svg'),
(14, 'es-se', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Diputacion_de_Sevilla_Spain.svg'),
(14, 'es-sg', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_Segovia_province.svg'),
(14, 'es-so', 'https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_Soria_province.svg'),
(14, 'es-ss', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Flag_of_Guip%C3%BAzcoa.svg'),
(14, 'es-te', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Teruel_%28province%29.svg'),
(14, 'es-tf', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Bandera_Provincial_de_Santa_Cruz_de_Tenerife.svg'),
(14, 'es-to', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Bandera_de_la_provincia_de_Toledo.svg'),
(14, 'es-t', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Diputaci%C3%B3_copy.jpg'),
(14, 'es-v', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Escut_de_la_Prov%C3%ADncia_de_Val%C3%A8ncia.svg'),
(14, 'es-va', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Bandera_de_la_provincia_de_Valladolid.svg'),
(14, 'es-vi', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_%C3%81lava.svg'),
(14, 'es-z', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Flag_of_Zaragoza_province_%28with_coat_of_arms%29.svg'),
(14, 'es-za', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Coat_of_Arms_of_Zamora_Province.svg'),
(15, 'ua-43', 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Crimea.svg'),
(15, 'ua-71', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Cherkasy_Oblast.svg'),
(15, 'ua-74', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Chernihiv_Oblast.svg'),
(15, 'ua-77', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Flag_of_Chernivtsi_Oblast.svg'),
(15, 'ua-12', 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Dnipropetrovsk_Oblast.svg'),
(15, 'ua-14', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Flag_of_Donetsk_Oblast.svg'),
(15, 'ua-26', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Ivano-Frankivsk_Oblast2.svg'),
(15, 'ua-63', 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Kharkiv_Oblast.svg'),
(15, 'ua-65', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_Kherson_Oblast.svg'),
(15, 'ua-68', 'https://upload.wikimedia.org/wikipedia/commons/3/37/Flag_of_Khmelnytskyi_Oblast.svg'),
(15, 'ua-32', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Flag_of_Kyiv_Oblast.svg'),
(15, 'ua-35', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Kirovohrad_Oblast.svg'),
(15, 'ua-09', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Luhansk_Oblast.svg'),
(15, 'ua-46', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Lviv_Oblast.svg'),
(15, 'ua-48', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Flag_of_Mykolaiv_Oblast.svg'),
(15, 'ua-51', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Odesa_Oblast.svg'),
(15, 'ua-53', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Poltava_Oblast.svg'),
(15, 'ua-56', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_Rivne_Oblast.svg'),
(15, 'ua-59', 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Sumy_Oblast.svg'),
(15, 'ua-61', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Flag_of_Ternopil_Oblast.svg'),
(15, 'ua-05', 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Vinnytsia_Oblast.svg'),
(15, 'ua-07', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Volyn_Oblast.svg'),
(15, 'ua-21', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_Transcarpathian_Oblast.svg'),
(15, 'ua-23', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Zaporizhia_Oblast.svg'),
(15, 'ua-18', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Zhytomyr_Oblast.svg'),
(16, 'us-al', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg'),
(16, 'us-ak', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg'),
(16, 'us-az', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg'),
(16, 'us-ar', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg'),
(16, 'us-ca', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg'),
(16, 'us-co', 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colorado_designed_by_Andrew_Carlisle_Carson.svg'),
(16, 'us-ct', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg'),
(16, 'us-de', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg'),
(16, 'us-fl', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg'),
(16, 'us-ga', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Georgia_(U.S._state).svg'),
(16, 'us-hi', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg'),
(16, 'us-id', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_Idaho.svg'),
(16, 'us-il', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg'),
(16, 'us-in', 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg'),
(16, 'us-ia', 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Iowa.svg'),
(16, 'us-ks', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Kansas.svg'),
(16, 'us-ky', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Flag_of_Kentucky.svg'),
(16, 'us-la', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg'),
(16, 'us-me', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Maine.svg'),
(16, 'us-md', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg'),
(16, 'us-ma', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Massachusetts.svg'),
(16, 'us-mi', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Michigan.svg'),
(16, 'us-mn', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Minnesota.svg'),
(16, 'us-ms', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_Mississippi.svg'),
(16, 'us-mo', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Missouri.svg'),
(16, 'us-mt', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Montana.svg'),
(16, 'us-ne', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Nebraska.svg'),
(16, 'us-nv', 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg'),
(16, 'us-nh', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_New_Hampshire.svg'),
(16, 'us-nj', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_New_Jersey.svg'),
(16, 'us-nm', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_New_Mexico.svg'),
(16, 'us-ny', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg'),
(16, 'us-nc', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg'),
(16, 'us-nd', 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Flag_of_North_Dakota.svg'),
(16, 'us-oh', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg'),
(16, 'us-ok', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg'),
(16, 'us-or', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg'),
(16, 'us-pa', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg'),
(16, 'us-ri', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg'),
(16, 'us-sc', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_South_Carolina.svg'),
(16, 'us-sd', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_South_Dakota.svg'),
(16, 'us-tn', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg'),
(16, 'us-tx', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg'),
(16, 'us-ut', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg'),
(16, 'us-vt', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Vermont.svg'),
(16, 'us-va', 'https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg'),
(16, 'us-wa', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg'),
(16, 'us-dc', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_the_District_of_Columbia.svg'),
(16, 'us-wv', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_West_Virginia.svg'),
(16, 'us-wi', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg'),
(16, 'us-wy', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg');
